---
- hosts: windows
  name: This is my Windows patching playbook
  connection: ssh
  vars:
    ansible_shell_type: powershell
  tasks:
    - name: Install Windows Updates
      win_updates:
        category_names: "{{ categories | default(omit) }}"
        reboot: "{{ reboot_server | default(yes) }}"
